package com.ezdi.cac.constant;

public interface TenantConfigConstant
{
	String SEARCH_SERVICE_URL = "SEARCH_SERVICE_URL";
	String SEARCH_SERVICE_MODULE = "SEARCH_SERVICE_MODULE";
	String SEARCH_SERVICE_AUTH_TOKEN = "SEARCH_SERVICE_AUTH_TOKEN";
	String SEARCH_SERVICE_CORE = "SEARCH_SERVICE_CORE";
	String HOSPITAL_TIMEZONE_ID = "HOSPITAL_TimeZone";
	String HOSPITAL_NAME = "HOSPITAL_Name";
}
